# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build: 
    docker:
      - image: circleci/python:3.7

    working_directory: ~/mernstarter
    # Checkout the code as the first step. This is a dedicated CircleCI step.
    # 
    # we're making sure we use just use the system-wide pip. By default it uses the project root's requirements.txt.
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      -  checkout
      - run:
          name: Install dependencies
          # This assumes pytest is installed via the install-package step above
          command:  |
             python3 -m venv venv
             mkdir -p venv/build
             touch venv/build/activate
             . venv/build/activate
             
             pip install -r requirements.txt

      # Create the test_results directory and set permissions before running tests
      - run:
          name: Prepare test results directory
          command: |
            mkdir -p /home/circleci/mernstarter/test-results
            chmod 777 /home/circleci/mernstarter/test-results

      - run:
          name: Run tests
          command:  |
             . venv/build/activate

             flake8  --exclude=venv*  --statistics

             pytest --junitxml=/home/circleci/mernstarter/test-results/junit.xml

      - store_test_results:
          path: /home/circleci/mernstarter/test-results

      - store_artifacts:
          path: /home/circleci/mernstarter/test-results

